DROP DATABASE  IF EXISTS nbr;

CREATE DATABASE nbr
CHARACTER   SET=utf8
COLLATE=utf8_unicode_ci;



DROP DATABASE IF EXISTS nbr_bx;

CREATE DATABASE nbr_bx
CHARACTER   SET=utf8
COLLATE=utf8_unicode_ci;
