package com.bx.erp.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "commodityCategory".
*/
public class CommodityCategoryDao extends AbstractDao<CommodityCategory, Long> {

    public static final String TABLENAME = "commodityCategory";

    /**
     * Properties of entity CommodityCategory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "F_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "F_Name");
        public final static Property ParentID = new Property(2, int.class, "parentID", false, "F_ParentID");
        public final static Property CreateDatetime = new Property(3, java.util.Date.class, "createDatetime", false, "F_CreateDatetime");
        public final static Property UpdateDatetime = new Property(4, java.util.Date.class, "updateDatetime", false, "F_UpdateDatetime");
        public final static Property SyncType = new Property(5, String.class, "syncType", false, "F_SyncType");
        public final static Property SyncDatetime = new Property(6, java.util.Date.class, "syncDatetime", false, "F_SyncDatetime");
    }


    public CommodityCategoryDao(DaoConfig config) {
        super(config);
    }
    
    public CommodityCategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"commodityCategory\" (" + //
                "\"F_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"F_Name\" TEXT NOT NULL ," + // 1: name
                "\"F_ParentID\" INTEGER NOT NULL ," + // 2: parentID
                "\"F_CreateDatetime\" INTEGER," + // 3: createDatetime
                "\"F_UpdateDatetime\" INTEGER," + // 4: updateDatetime
                "\"F_SyncType\" TEXT," + // 5: syncType
                "\"F_SyncDatetime\" INTEGER);"); // 6: syncDatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"commodityCategory\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CommodityCategory entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getParentID());
 
        java.util.Date createDatetime = entity.getCreateDatetime();
        if (createDatetime != null) {
            stmt.bindLong(4, createDatetime.getTime());
        }
 
        java.util.Date updateDatetime = entity.getUpdateDatetime();
        if (updateDatetime != null) {
            stmt.bindLong(5, updateDatetime.getTime());
        }
 
        String syncType = entity.getSyncType();
        if (syncType != null) {
            stmt.bindString(6, syncType);
        }
 
        java.util.Date syncDatetime = entity.getSyncDatetime();
        if (syncDatetime != null) {
            stmt.bindLong(7, syncDatetime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CommodityCategory entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getParentID());
 
        java.util.Date createDatetime = entity.getCreateDatetime();
        if (createDatetime != null) {
            stmt.bindLong(4, createDatetime.getTime());
        }
 
        java.util.Date updateDatetime = entity.getUpdateDatetime();
        if (updateDatetime != null) {
            stmt.bindLong(5, updateDatetime.getTime());
        }
 
        String syncType = entity.getSyncType();
        if (syncType != null) {
            stmt.bindString(6, syncType);
        }
 
        java.util.Date syncDatetime = entity.getSyncDatetime();
        if (syncDatetime != null) {
            stmt.bindLong(7, syncDatetime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CommodityCategory readEntity(Cursor cursor, int offset) {
        CommodityCategory entity = new CommodityCategory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // parentID
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // createDatetime
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // updateDatetime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // syncType
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // syncDatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CommodityCategory entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setParentID(cursor.getInt(offset + 2));
        entity.setCreateDatetime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdateDatetime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setSyncType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSyncDatetime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CommodityCategory entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CommodityCategory entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CommodityCategory entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
