package com.bx.erp.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "retailTradeCoupon".
*/
public class RetailTradeCouponDao extends AbstractDao<RetailTradeCoupon, Long> {

    public static final String TABLENAME = "retailTradeCoupon";

    /**
     * Properties of entity RetailTradeCoupon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "F_ID");
        public final static Property RetailTradeID = new Property(1, int.class, "retailTradeID", false, "F_RetailTradeID");
        public final static Property CouponCodeID = new Property(2, int.class, "couponCodeID", false, "F_CouponCodeID");
        public final static Property SyncDatetime = new Property(3, java.util.Date.class, "syncDatetime", false, "F_SyncDatetime");
    }


    public RetailTradeCouponDao(DaoConfig config) {
        super(config);
    }
    
    public RetailTradeCouponDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"retailTradeCoupon\" (" + //
                "\"F_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"F_RetailTradeID\" INTEGER NOT NULL ," + // 1: retailTradeID
                "\"F_CouponCodeID\" INTEGER NOT NULL ," + // 2: couponCodeID
                "\"F_SyncDatetime\" INTEGER);"); // 3: syncDatetime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"retailTradeCoupon\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RetailTradeCoupon entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getRetailTradeID());
        stmt.bindLong(3, entity.getCouponCodeID());
 
        java.util.Date syncDatetime = entity.getSyncDatetime();
        if (syncDatetime != null) {
            stmt.bindLong(4, syncDatetime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RetailTradeCoupon entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getRetailTradeID());
        stmt.bindLong(3, entity.getCouponCodeID());
 
        java.util.Date syncDatetime = entity.getSyncDatetime();
        if (syncDatetime != null) {
            stmt.bindLong(4, syncDatetime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RetailTradeCoupon readEntity(Cursor cursor, int offset) {
        RetailTradeCoupon entity = new RetailTradeCoupon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getInt(offset + 1), // retailTradeID
            cursor.getInt(offset + 2), // couponCodeID
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)) // syncDatetime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RetailTradeCoupon entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRetailTradeID(cursor.getInt(offset + 1));
        entity.setCouponCodeID(cursor.getInt(offset + 2));
        entity.setSyncDatetime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RetailTradeCoupon entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RetailTradeCoupon entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RetailTradeCoupon entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
