package com.bx.erp.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "T_Barcodes".
*/
public class BarcodesDao extends AbstractDao<Barcodes, Long> {

    public static final String TABLENAME = "T_Barcodes";

    /**
     * Properties of entity Barcodes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "F_ID");
        public final static Property CommodityID = new Property(1, int.class, "commodityID", false, "F_CommodityID");
        public final static Property Barcode = new Property(2, String.class, "barcode", false, "F_Barcode");
        public final static Property CreateDatetime = new Property(3, java.util.Date.class, "createDatetime", false, "F_CreateDatetime");
        public final static Property UpdateDatetime = new Property(4, java.util.Date.class, "updateDatetime", false, "F_UpdateDatetime");
        public final static Property SyncDatetime = new Property(5, java.util.Date.class, "syncDatetime", false, "F_SyncDatetime");
        public final static Property SyncType = new Property(6, String.class, "syncType", false, "F_SyncType");
    }


    public BarcodesDao(DaoConfig config) {
        super(config);
    }
    
    public BarcodesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"T_Barcodes\" (" + //
                "\"F_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"F_CommodityID\" INTEGER NOT NULL ," + // 1: commodityID
                "\"F_Barcode\" TEXT NOT NULL ," + // 2: barcode
                "\"F_CreateDatetime\" INTEGER," + // 3: createDatetime
                "\"F_UpdateDatetime\" INTEGER," + // 4: updateDatetime
                "\"F_SyncDatetime\" INTEGER," + // 5: syncDatetime
                "\"F_SyncType\" TEXT);"); // 6: syncType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"T_Barcodes\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Barcodes entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getCommodityID());
        stmt.bindString(3, entity.getBarcode());
 
        java.util.Date createDatetime = entity.getCreateDatetime();
        if (createDatetime != null) {
            stmt.bindLong(4, createDatetime.getTime());
        }
 
        java.util.Date updateDatetime = entity.getUpdateDatetime();
        if (updateDatetime != null) {
            stmt.bindLong(5, updateDatetime.getTime());
        }
 
        java.util.Date syncDatetime = entity.getSyncDatetime();
        if (syncDatetime != null) {
            stmt.bindLong(6, syncDatetime.getTime());
        }
 
        String syncType = entity.getSyncType();
        if (syncType != null) {
            stmt.bindString(7, syncType);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Barcodes entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getCommodityID());
        stmt.bindString(3, entity.getBarcode());
 
        java.util.Date createDatetime = entity.getCreateDatetime();
        if (createDatetime != null) {
            stmt.bindLong(4, createDatetime.getTime());
        }
 
        java.util.Date updateDatetime = entity.getUpdateDatetime();
        if (updateDatetime != null) {
            stmt.bindLong(5, updateDatetime.getTime());
        }
 
        java.util.Date syncDatetime = entity.getSyncDatetime();
        if (syncDatetime != null) {
            stmt.bindLong(6, syncDatetime.getTime());
        }
 
        String syncType = entity.getSyncType();
        if (syncType != null) {
            stmt.bindString(7, syncType);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Barcodes readEntity(Cursor cursor, int offset) {
        Barcodes entity = new Barcodes( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getInt(offset + 1), // commodityID
            cursor.getString(offset + 2), // barcode
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // createDatetime
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // updateDatetime
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // syncDatetime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // syncType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Barcodes entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCommodityID(cursor.getInt(offset + 1));
        entity.setBarcode(cursor.getString(offset + 2));
        entity.setCreateDatetime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdateDatetime(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setSyncDatetime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setSyncType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Barcodes entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Barcodes entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Barcodes entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
