package wpos.helper;

public class ASCII {

    public static final char CHAR_NUM_0 = 48;
    public static final char CHAR_NUM_1 = 49;
    public static final char CHAR_NUM_2 = 50;
    public static final char CHAR_NUM_3 = 51;
    public static final char CHAR_NUM_4 = 52;
    public static final char CHAR_NUM_5 = 53;
    public static final char CHAR_NUM_6 = 54;
    public static final char CHAR_NUM_7 = 55;
    public static final char CHAR_NUM_8 = 56;
    public static final char CHAR_NUM_9 = 57;

    public static final char CHAR_LETTER_A = 65; // 大写字母A　
    public static final char CHAR_LETTER_B = 66; // 大写字母B
    public static final char CHAR_LETTER_C = 67; // 大写字母C
    public static final char CHAR_LETTER_D = 68; // 大写字母D
    public static final char CHAR_LETTER_E = 69; // 大写字母E
    public static final char CHAR_LETTER_F = 70; // 大写字母F
    public static final char CHAR_LETTER_G = 71; // 大写字母G
    public static final char CHAR_LETTER_H = 72; // 大写字母H
    public static final char CHAR_LETTER_I = 73; // 大写字母I
    public static final char CHAR_LETTER_J = 74; // 大写字母J
    public static final char CHAR_LETTER_K = 75; // 大写字母K
    public static final char CHAR_LETTER_L = 76; // 大写字母L
    public static final char CHAR_LETTER_M = 77; // 大写字母M
    public static final char CHAR_LETTER_N = 78; // 大写字母N
    public static final char CHAR_LETTER_O = 79; // 大写字母O
    public static final char CHAR_LETTER_P = 80; // 大写字母P
    public static final char CHAR_LETTER_Q = 81; // 大写字母Q
    public static final char CHAR_LETTER_R = 82; // 大写字母R
    public static final char CHAR_LETTER_S = 83; // 大写字母S
    public static final char CHAR_LETTER_T = 84; // 大写字母T
    public static final char CHAR_LETTER_U = 85; // 大写字母U
    public static final char CHAR_LETTER_V = 86; // 大写字母V
    public static final char CHAR_LETTER_W = 87; // 大写字母W
    public static final char CHAR_LETTER_X = 88; // 大写字母X
    public static final char CHAR_LETTER_Y = 89; // 大写字母Y
    public static final char CHAR_LETTER_Z = 90; // 大写字母Z

    public static final char CHAR_LETTER_a = 97; // 小写字母a　
    public static final char CHAR_LETTER_b = 98;
    public static final char CHAR_LETTER_c = 99;
    public static final char CHAR_LETTER_d = 100; // 小写字母d
    public static final char CHAR_LETTER_e = 101; // 小写字母e
    public static final char CHAR_LETTER_f = 102; // 小写字母f
    public static final char CHAR_LETTER_g = 103; // 小写字母g
    public static final char CHAR_LETTER_h = 104; // 小写字母h
    public static final char CHAR_LETTER_i = 105; // 小写字母i
    public static final char CHAR_LETTER_j = 106; // 小写字母j
    public static final char CHAR_LETTER_k = 107; // 小写字母k
    public static final char CHAR_LETTER_l = 108; // 小写字母l
    public static final char CHAR_LETTER_m = 109; // 小写字母m
    public static final char CHAR_LETTER_n = 110; // 小写字母n
    public static final char CHAR_LETTER_o = 111; // 小写字母o
    public static final char CHAR_LETTER_p = 112; // 小写字母p
    public static final char CHAR_LETTER_q = 113; // 小写字母q
    public static final char CHAR_LETTER_r = 114; // 小写字母r
    public static final char CHAR_LETTER_s = 115; // 小写字母s
    public static final char CHAR_LETTER_t = 116; // 小写字母t
    public static final char CHAR_LETTER_u = 117; // 小写字母u
    public static final char CHAR_LETTER_v = 118; // 小写字母v
    public static final char CHAR_LETTER_w = 119; // 小写字母w
    public static final char CHAR_LETTER_x = 120; // 小写字母x
    public static final char CHAR_LETTER_y = 121; // 小写字母y
    public static final char CHAR_LETTER_z = 122; // 小写字母z

    public static final char CHAR_SIGN_NUL = 0; // 空字符 null
    public static final char CHAR_SIGN_SOH = 1; // 标题开始 start of headline
    public static final char CHAR_SIGN_STX = 2; // 正文开始 start of text
    public static final char CHAR_SIGN_ETX = 3; // 正文结束 end of text
    public static final char CHAR_SIGN_EOT = 4; // 传输结束 end of transmission
    public static final char CHAR_SIGN_ENQ = 5; // 请求 enquiry
    public static final char CHAR_SIGN_ACK = 6; // 收到通知 acknowledge
    public static final char CHAR_SIGN_BEL = 7; // 响铃 bell
    public static final char CHAR_SIGN_BS = 8; // 退格 backspace
    public static final char CHAR_SIGN_HT = 9; // 水平制表符 horizontal tab
    public static final char CHAR_SIGN_LF = 10; // 换行键 NL line feed, new line
    public static final char CHAR_SIGN_VT = 11; // 垂直制表符 vertical tab
    public static final char CHAR_SIGN_FF = 12; // 换页键 NP form feed, new page
    public static final char CHAR_SIGN_CR = 13; // 回车键 carriage return
    public static final char CHAR_SIGN_SO = 14; // 不用切换 shift out
    public static final char CHAR_SIGN_SI = 15; // 启用切换 shift in
    public static final char CHAR_SIGN_DLE = 16; // 数据链路转义 data link escape
    public static final char CHAR_SIGN_DC1 = 17; // 设备控制1 device control 1
    public static final char CHAR_SIGN_DC2 = 18; // 设备控制2 device control 2
    public static final char CHAR_SIGN_DC3 = 19; // 设备控制3 device control 3
    public static final char CHAR_SIGN_DC4 = 20; // 设备控制4 device control 4
    public static final char CHAR_SIGN_NAK = 21; // 拒绝接收 negative acknowledge
    public static final char CHAR_SIGN_SYN = 22; // 同步空闲 synchronous idle
    public static final char CHAR_SIGN_ETB = 23; // 结束传输块 end of trans. block
    public static final char CHAR_SIGN_CAN = 24; // 取消 cancel
    public static final char CHAR_SIGN_EM = 25; // 媒介结束 end of medium
    public static final char CHAR_SIGN_SUB = 26; // 代替 substitute
    public static final char CHAR_SIGN_ESC = 27; // 换码(溢出) escape
    public static final char CHAR_SIGN_FS = 28; // 文件分隔符 file separator
    public static final char CHAR_SIGN_GS = 29; // 分组符 group separator
    public static final char CHAR_SIGN_RS = 30; // 记录分隔符 record separator
    public static final char CHAR_SIGN_US = 31; // 单元分隔符 unit separator
    public static final char CHAR_SIGN_SPACE = 32; // 空格
    public static final char CHAR_SIGN_EXCLAM = 33; // 叹号
    public static final char CHAR_SIGN_DOUBLE_QUOTE = 34; // 双引号
    public static final char CHAR_SIGN_HASH = 35; // 井号
    public static final char CHAR_SIGN_DOLLAR = 36; // 美元符
    public static final char CHAR_SIGN_PERCENT = 37; // 百分号
    public static final char CHAR_SIGN_AMPERSAND = 38; // 和号
    public static final char CHAR_SIGN_QUOTE = 39; // 单引号
    public static final char CHAR_SIGN_PAREN_LEFT = 40; // 开括号
    public static final char CHAR_SIGN_PAREN_RIGHT = 41; // 闭括号
    public static final char CHAR_SIGN_STAR = 42; // 星号
    public static final char CHAR_SIGN_PLUS = 43; // 加号
    public static final char CHAR_SIGN_COMMA = 44; // 逗号
    public static final char CHAR_SIGN_MINUS = 45; // 减号/破折号
    public static final char CHAR_SIGN_PERIOD = 46; // 句号
    public static final char CHAR_SIGN_SLASH = 47; // 斜杠
    public static final char CHAR_SIGN_COLON = 58; // 冒号
    public static final char CHAR_SIGN_SEMICOLON = 59; // 分号
    public static final char CHAR_SIGN_LESS = 60; // 小于
    public static final char CHAR_SIGN_EQUALS = 61; // 等号
    public static final char CHAR_SIGN_GREATER = 62; // 大于
    public static final char CHAR_SIGN_QUESTION = 63; // 问号
    public static final char CHAR_SIGN_AT = 64; // 电子邮件符号
    public static final char CHAR_SIGN_BRACKET_LEFT = 91; // 开方括号
    public static final char CHAR_SIGN_BACKSLASH = 92; // 反斜杠
    public static final char CHAR_SIGN_BRACKET_RIGHT = 93; // 闭方括号
    public static final char CHAR_SIGN_CARET = 94; // 脱字符
    public static final char CHAR_SIGN_UNDERSCORE = 95; // 下划线
    public static final char CHAR_SIGN_BACKTICK = 96; // 重音符`
    public static final char CHAR_SIGN_BRACE_LEFT = 123; // 开花括号
    public static final char CHAR_SIGN_BAR = 124; // 垂线
    public static final char CHAR_SIGN_BRACE_RIGHT = 125; // 闭花括号
    public static final char CHAR_SIGN_TILDE = 126; // 波浪号
    public static final char CHAR_SIGN_DELETE = 127; // 删除 (delete)
}

