//package wpos.model;
//
//import java.util.Map;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import wpos.model.Barcodes;
//import wpos.model.Brand;
//import wpos.model.BXConfigGeneral;
//import wpos.model.Commodity;
//import wpos.model.CommodityCategory;
//import wpos.model.Company;
//import wpos.model.ConfigCacheSize;
//import wpos.model.ConfigGeneral;
//import wpos.model.Ntp;
//import wpos.model.PackageUnit;
//import wpos.model.Pos;
//import wpos.model.Promotion;
//import wpos.model.PromotionScope;
//import wpos.model.PurchasingOrder;
//import wpos.model.PurchasingOrderCommodity;
//import wpos.model.RetailTrade;
//import wpos.model.RetailTradeAggregation;
//import wpos.model.RetailTradeCommodity;
//import wpos.model.RetailTradePromoting;
//import wpos.model.RetailTradePromotingFlow;
//import wpos.model.ReturnCommoditySheet;
//import wpos.model.Shop;
//import wpos.model.SmallSheetFrame;
//import wpos.model.SmallSheetText;
//import wpos.model.Staff;
//import wpos.model.Vip;
//import wpos.model.VipCategory;
//import wpos.model.Warehousing;
//import wpos.model.WarehousingCommodity;
//
//import wpos.model.BarcodesDao;
//import wpos.model.BrandDao;
//import wpos.model.BXConfigGeneralDao;
//import wpos.model.CommodityDao;
//import wpos.model.CommodityCategoryDao;
//import wpos.model.CompanyDao;
//import wpos.model.ConfigCacheSizeDao;
//import wpos.model.ConfigGeneralDao;
//import wpos.model.NtpDao;
//import wpos.model.PackageUnitDao;
//import wpos.model.PosDao;
//import wpos.model.PromotionDao;
//import wpos.model.PromotionScopeDao;
//import wpos.model.PurchasingOrderDao;
//import wpos.model.PurchasingOrderCommodityDao;
//import wpos.model.RetailTradeDao;
//import wpos.model.RetailTradeAggregationDao;
//import wpos.model.RetailTradeCommodityDao;
//import wpos.model.RetailTradePromotingDao;
//import wpos.model.RetailTradePromotingFlowDao;
//import wpos.model.ReturnCommoditySheetDao;
//import wpos.model.ShopDao;
//import wpos.model.SmallSheetFrameDao;
//import wpos.model.SmallSheetTextDao;
//import wpos.model.StaffDao;
//import wpos.model.VipDao;
//import wpos.model.VipCategoryDao;
//import wpos.model.WarehousingDao;
//import wpos.model.WarehousingCommodityDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see org.greenrobot.greendao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig barcodesDaoConfig;
//    private final DaoConfig brandDaoConfig;
//    private final DaoConfig bXConfigGeneralDaoConfig;
//    private final DaoConfig commodityDaoConfig;
//    private final DaoConfig commodityCategoryDaoConfig;
//    private final DaoConfig companyDaoConfig;
//    private final DaoConfig configCacheSizeDaoConfig;
//    private final DaoConfig configGeneralDaoConfig;
//    private final DaoConfig ntpDaoConfig;
//    private final DaoConfig packageUnitDaoConfig;
//    private final DaoConfig posDaoConfig;
//    private final DaoConfig promotionDaoConfig;
//    private final DaoConfig promotionScopeDaoConfig;
//    private final DaoConfig purchasingOrderDaoConfig;
//    private final DaoConfig purchasingOrderCommodityDaoConfig;
//    private final DaoConfig retailTradeDaoConfig;
//    private final DaoConfig retailTradeAggregationDaoConfig;
//    private final DaoConfig retailTradeCommodityDaoConfig;
//    private final DaoConfig retailTradePromotingDaoConfig;
//    private final DaoConfig retailTradePromotingFlowDaoConfig;
//    private final DaoConfig returnCommoditySheetDaoConfig;
//    private final DaoConfig shopDaoConfig;
//    private final DaoConfig smallSheetFrameDaoConfig;
//    private final DaoConfig smallSheetTextDaoConfig;
//    private final DaoConfig staffDaoConfig;
//    private final DaoConfig vipDaoConfig;
//    private final DaoConfig vipCategoryDaoConfig;
//    private final DaoConfig warehousingDaoConfig;
//    private final DaoConfig warehousingCommodityDaoConfig;
//
//    private final BarcodesDao barcodesDao;
//    private final BrandDao brandDao;
//    private final BXConfigGeneralDao bXConfigGeneralDao;
//    private final CommodityDao commodityDao;
//    private final CommodityCategoryDao commodityCategoryDao;
//    private final CompanyDao companyDao;
//    private final ConfigCacheSizeDao configCacheSizeDao;
//    private final ConfigGeneralDao configGeneralDao;
//    private final NtpDao ntpDao;
//    private final PackageUnitDao packageUnitDao;
//    private final PosDao posDao;
//    private final PromotionDao promotionDao;
//    private final PromotionScopeDao promotionScopeDao;
//    private final PurchasingOrderDao purchasingOrderDao;
//    private final PurchasingOrderCommodityDao purchasingOrderCommodityDao;
//    private final RetailTradeDao retailTradeDao;
//    private final RetailTradeAggregationDao retailTradeAggregationDao;
//    private final RetailTradeCommodityDao retailTradeCommodityDao;
//    private final RetailTradePromotingDao retailTradePromotingDao;
//    private final RetailTradePromotingFlowDao retailTradePromotingFlowDao;
//    private final ReturnCommoditySheetDao returnCommoditySheetDao;
//    private final ShopDao shopDao;
//    private final SmallSheetFrameDao smallSheetFrameDao;
//    private final SmallSheetTextDao smallSheetTextDao;
//    private final StaffDao staffDao;
//    private final VipDao vipDao;
//    private final VipCategoryDao vipCategoryDao;
//    private final WarehousingDao warehousingDao;
//    private final WarehousingCommodityDao warehousingCommodityDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        barcodesDaoConfig = daoConfigMap.get(BarcodesDao.class).clone();
//        barcodesDaoConfig.initIdentityScope(type);
//
//        brandDaoConfig = daoConfigMap.get(BrandDao.class).clone();
//        brandDaoConfig.initIdentityScope(type);
//
//        bXConfigGeneralDaoConfig = daoConfigMap.get(BXConfigGeneralDao.class).clone();
//        bXConfigGeneralDaoConfig.initIdentityScope(type);
//
//        commodityDaoConfig = daoConfigMap.get(CommodityDao.class).clone();
//        commodityDaoConfig.initIdentityScope(type);
//
//        commodityCategoryDaoConfig = daoConfigMap.get(CommodityCategoryDao.class).clone();
//        commodityCategoryDaoConfig.initIdentityScope(type);
//
//        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
//        companyDaoConfig.initIdentityScope(type);
//
//        configCacheSizeDaoConfig = daoConfigMap.get(ConfigCacheSizeDao.class).clone();
//        configCacheSizeDaoConfig.initIdentityScope(type);
//
//        configGeneralDaoConfig = daoConfigMap.get(ConfigGeneralDao.class).clone();
//        configGeneralDaoConfig.initIdentityScope(type);
//
//        ntpDaoConfig = daoConfigMap.get(NtpDao.class).clone();
//        ntpDaoConfig.initIdentityScope(type);
//
//        packageUnitDaoConfig = daoConfigMap.get(PackageUnitDao.class).clone();
//        packageUnitDaoConfig.initIdentityScope(type);
//
//        posDaoConfig = daoConfigMap.get(PosDao.class).clone();
//        posDaoConfig.initIdentityScope(type);
//
//        promotionDaoConfig = daoConfigMap.get(PromotionDao.class).clone();
//        promotionDaoConfig.initIdentityScope(type);
//
//        promotionScopeDaoConfig = daoConfigMap.get(PromotionScopeDao.class).clone();
//        promotionScopeDaoConfig.initIdentityScope(type);
//
//        purchasingOrderDaoConfig = daoConfigMap.get(PurchasingOrderDao.class).clone();
//        purchasingOrderDaoConfig.initIdentityScope(type);
//
//        purchasingOrderCommodityDaoConfig = daoConfigMap.get(PurchasingOrderCommodityDao.class).clone();
//        purchasingOrderCommodityDaoConfig.initIdentityScope(type);
//
//        retailTradeDaoConfig = daoConfigMap.get(RetailTradeDao.class).clone();
//        retailTradeDaoConfig.initIdentityScope(type);
//
//        retailTradeAggregationDaoConfig = daoConfigMap.get(RetailTradeAggregationDao.class).clone();
//        retailTradeAggregationDaoConfig.initIdentityScope(type);
//
//        retailTradeCommodityDaoConfig = daoConfigMap.get(RetailTradeCommodityDao.class).clone();
//        retailTradeCommodityDaoConfig.initIdentityScope(type);
//
//        retailTradePromotingDaoConfig = daoConfigMap.get(RetailTradePromotingDao.class).clone();
//        retailTradePromotingDaoConfig.initIdentityScope(type);
//
//        retailTradePromotingFlowDaoConfig = daoConfigMap.get(RetailTradePromotingFlowDao.class).clone();
//        retailTradePromotingFlowDaoConfig.initIdentityScope(type);
//
//        returnCommoditySheetDaoConfig = daoConfigMap.get(ReturnCommoditySheetDao.class).clone();
//        returnCommoditySheetDaoConfig.initIdentityScope(type);
//
//        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
//        shopDaoConfig.initIdentityScope(type);
//
//        smallSheetFrameDaoConfig = daoConfigMap.get(SmallSheetFrameDao.class).clone();
//        smallSheetFrameDaoConfig.initIdentityScope(type);
//
//        smallSheetTextDaoConfig = daoConfigMap.get(SmallSheetTextDao.class).clone();
//        smallSheetTextDaoConfig.initIdentityScope(type);
//
//        staffDaoConfig = daoConfigMap.get(StaffDao.class).clone();
//        staffDaoConfig.initIdentityScope(type);
//
//        vipDaoConfig = daoConfigMap.get(VipDao.class).clone();
//        vipDaoConfig.initIdentityScope(type);
//
//        vipCategoryDaoConfig = daoConfigMap.get(VipCategoryDao.class).clone();
//        vipCategoryDaoConfig.initIdentityScope(type);
//
//        warehousingDaoConfig = daoConfigMap.get(WarehousingDao.class).clone();
//        warehousingDaoConfig.initIdentityScope(type);
//
//        warehousingCommodityDaoConfig = daoConfigMap.get(WarehousingCommodityDao.class).clone();
//        warehousingCommodityDaoConfig.initIdentityScope(type);
//
//        barcodesDao = new BarcodesDao(barcodesDaoConfig, this);
//        brandDao = new BrandDao(brandDaoConfig, this);
//        bXConfigGeneralDao = new BXConfigGeneralDao(bXConfigGeneralDaoConfig, this);
//        commodityDao = new CommodityDao(commodityDaoConfig, this);
//        commodityCategoryDao = new CommodityCategoryDao(commodityCategoryDaoConfig, this);
//        companyDao = new CompanyDao(companyDaoConfig, this);
//        configCacheSizeDao = new ConfigCacheSizeDao(configCacheSizeDaoConfig, this);
//        configGeneralDao = new ConfigGeneralDao(configGeneralDaoConfig, this);
//        ntpDao = new NtpDao(ntpDaoConfig, this);
//        packageUnitDao = new PackageUnitDao(packageUnitDaoConfig, this);
//        posDao = new PosDao(posDaoConfig, this);
//        promotionDao = new PromotionDao(promotionDaoConfig, this);
//        promotionScopeDao = new PromotionScopeDao(promotionScopeDaoConfig, this);
//        purchasingOrderDao = new PurchasingOrderDao(purchasingOrderDaoConfig, this);
//        purchasingOrderCommodityDao = new PurchasingOrderCommodityDao(purchasingOrderCommodityDaoConfig, this);
//        retailTradeDao = new RetailTradeDao(retailTradeDaoConfig, this);
//        retailTradeAggregationDao = new RetailTradeAggregationDao(retailTradeAggregationDaoConfig, this);
//        retailTradeCommodityDao = new RetailTradeCommodityDao(retailTradeCommodityDaoConfig, this);
//        retailTradePromotingDao = new RetailTradePromotingDao(retailTradePromotingDaoConfig, this);
//        retailTradePromotingFlowDao = new RetailTradePromotingFlowDao(retailTradePromotingFlowDaoConfig, this);
//        returnCommoditySheetDao = new ReturnCommoditySheetDao(returnCommoditySheetDaoConfig, this);
//        shopDao = new ShopDao(shopDaoConfig, this);
//        smallSheetFrameDao = new SmallSheetFrameDao(smallSheetFrameDaoConfig, this);
//        smallSheetTextDao = new SmallSheetTextDao(smallSheetTextDaoConfig, this);
//        staffDao = new StaffDao(staffDaoConfig, this);
//        vipDao = new VipDao(vipDaoConfig, this);
//        vipCategoryDao = new VipCategoryDao(vipCategoryDaoConfig, this);
//        warehousingDao = new WarehousingDao(warehousingDaoConfig, this);
//        warehousingCommodityDao = new WarehousingCommodityDao(warehousingCommodityDaoConfig, this);
//
//        registerDao(Barcodes.class, barcodesDao);
//        registerDao(Brand.class, brandDao);
//        registerDao(BXConfigGeneral.class, bXConfigGeneralDao);
//        registerDao(Commodity.class, commodityDao);
//        registerDao(CommodityCategory.class, commodityCategoryDao);
//        registerDao(Company.class, companyDao);
//        registerDao(ConfigCacheSize.class, configCacheSizeDao);
//        registerDao(ConfigGeneral.class, configGeneralDao);
//        registerDao(Ntp.class, ntpDao);
//        registerDao(PackageUnit.class, packageUnitDao);
//        registerDao(Pos.class, posDao);
//        registerDao(Promotion.class, promotionDao);
//        registerDao(PromotionScope.class, promotionScopeDao);
//        registerDao(PurchasingOrder.class, purchasingOrderDao);
//        registerDao(PurchasingOrderCommodity.class, purchasingOrderCommodityDao);
//        registerDao(RetailTrade.class, retailTradeDao);
//        registerDao(RetailTradeAggregation.class, retailTradeAggregationDao);
//        registerDao(RetailTradeCommodity.class, retailTradeCommodityDao);
//        registerDao(RetailTradePromoting.class, retailTradePromotingDao);
//        registerDao(RetailTradePromotingFlow.class, retailTradePromotingFlowDao);
//        registerDao(ReturnCommoditySheet.class, returnCommoditySheetDao);
//        registerDao(Shop.class, shopDao);
//        registerDao(SmallSheetFrame.class, smallSheetFrameDao);
//        registerDao(SmallSheetText.class, smallSheetTextDao);
//        registerDao(Staff.class, staffDao);
//        registerDao(Vip.class, vipDao);
//        registerDao(VipCategory.class, vipCategoryDao);
//        registerDao(Warehousing.class, warehousingDao);
//        registerDao(WarehousingCommodity.class, warehousingCommodityDao);
//    }
//
//    public void clear() {
//        barcodesDaoConfig.clearIdentityScope();
//        brandDaoConfig.clearIdentityScope();
//        bXConfigGeneralDaoConfig.clearIdentityScope();
//        commodityDaoConfig.clearIdentityScope();
//        commodityCategoryDaoConfig.clearIdentityScope();
//        companyDaoConfig.clearIdentityScope();
//        configCacheSizeDaoConfig.clearIdentityScope();
//        configGeneralDaoConfig.clearIdentityScope();
//        ntpDaoConfig.clearIdentityScope();
//        packageUnitDaoConfig.clearIdentityScope();
//        posDaoConfig.clearIdentityScope();
//        promotionDaoConfig.clearIdentityScope();
//        promotionScopeDaoConfig.clearIdentityScope();
//        purchasingOrderDaoConfig.clearIdentityScope();
//        purchasingOrderCommodityDaoConfig.clearIdentityScope();
//        retailTradeDaoConfig.clearIdentityScope();
//        retailTradeAggregationDaoConfig.clearIdentityScope();
//        retailTradeCommodityDaoConfig.clearIdentityScope();
//        retailTradePromotingDaoConfig.clearIdentityScope();
//        retailTradePromotingFlowDaoConfig.clearIdentityScope();
//        returnCommoditySheetDaoConfig.clearIdentityScope();
//        shopDaoConfig.clearIdentityScope();
//        smallSheetFrameDaoConfig.clearIdentityScope();
//        smallSheetTextDaoConfig.clearIdentityScope();
//        staffDaoConfig.clearIdentityScope();
//        vipDaoConfig.clearIdentityScope();
//        vipCategoryDaoConfig.clearIdentityScope();
//        warehousingDaoConfig.clearIdentityScope();
//        warehousingCommodityDaoConfig.clearIdentityScope();
//    }
//
//    public BarcodesDao getBarcodesDao() {
//        return barcodesDao;
//    }
//
//    public BrandDao getBrandDao() {
//        return brandDao;
//    }
//
//    public BXConfigGeneralDao getBXConfigGeneralDao() {
//        return bXConfigGeneralDao;
//    }
//
//    public CommodityDao getCommodityDao() {
//        return commodityDao;
//    }
//
//    public CommodityCategoryDao getCommodityCategoryDao() {
//        return commodityCategoryDao;
//    }
//
//    public CompanyDao getCompanyDao() {
//        return companyDao;
//    }
//
//    public ConfigCacheSizeDao getConfigCacheSizeDao() {
//        return configCacheSizeDao;
//    }
//
//    public ConfigGeneralDao getConfigGeneralDao() {
//        return configGeneralDao;
//    }
//
//    public NtpDao getNtpDao() {
//        return ntpDao;
//    }
//
//    public PackageUnitDao getPackageUnitDao() {
//        return packageUnitDao;
//    }
//
//    public PosDao getPosDao() {
//        return posDao;
//    }
//
//    public PromotionDao getPromotionDao() {
//        return promotionDao;
//    }
//
//    public PromotionScopeDao getPromotionScopeDao() {
//        return promotionScopeDao;
//    }
//
//    public PurchasingOrderDao getPurchasingOrderDao() {
//        return purchasingOrderDao;
//    }
//
//    public PurchasingOrderCommodityDao getPurchasingOrderCommodityDao() {
//        return purchasingOrderCommodityDao;
//    }
//
//    public RetailTradeDao getRetailTradeDao() {
//        return retailTradeDao;
//    }
//
//    public RetailTradeAggregationDao getRetailTradeAggregationDao() {
//        return retailTradeAggregationDao;
//    }
//
//    public RetailTradeCommodityDao getRetailTradeCommodityDao() {
//        return retailTradeCommodityDao;
//    }
//
//    public RetailTradePromotingDao getRetailTradePromotingDao() {
//        return retailTradePromotingDao;
//    }
//
//    public RetailTradePromotingFlowDao getRetailTradePromotingFlowDao() {
//        return retailTradePromotingFlowDao;
//    }
//
//    public ReturnCommoditySheetDao getReturnCommoditySheetDao() {
//        return returnCommoditySheetDao;
//    }
//
//    public ShopDao getShopDao() {
//        return shopDao;
//    }
//
//    public SmallSheetFrameDao getSmallSheetFrameDao() {
//        return smallSheetFrameDao;
//    }
//
//    public SmallSheetTextDao getSmallSheetTextDao() {
//        return smallSheetTextDao;
//    }
//
//    public StaffDao getStaffDao() {
//        return staffDao;
//    }
//
//    public VipDao getVipDao() {
//        return vipDao;
//    }
//
//    public VipCategoryDao getVipCategoryDao() {
//        return vipCategoryDao;
//    }
//
//    public WarehousingDao getWarehousingDao() {
//        return warehousingDao;
//    }
//
//    public WarehousingCommodityDao getWarehousingCommodityDao() {
//        return warehousingCommodityDao;
//    }
//
//}
