-- 该SP是直接获取所有的Card_ID信息到缓存，所以不需要分页
--	DROP PROCEDURE IF EXISTS `SP_VipBelonging_RetrieveN`;
--	CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_VipBelonging_RetrieveN` (
--		OUT iErrorCode INT,
--		OUT sErrorMsg VARCHAR(64)
--	)
--	BEGIN
--		DECLARE EXIT HANDLER FOR SQLEXCEPTION 
--		BEGIN
--			SET iErrorCode := 3;
--			SET sErrorMsg := '数据库错误';
--			ROLLBACK;
--		END;
--		
--		START TRANSACTION;
--			
--			SELECT * FROM (
--				(SELECT F_CardID, database() AS 'dbName' FROM t_wxcoupon)
--			UNION
--				(SELECT F_CardID, database() AS 'dbName' FROM t_wxcard) 
--			) AS tmp1;
--			
--		  	SET iErrorCode := 0;
--			SET sErrorMsg := '';
--			
--		COMMIT;
--	END;