--	-- 该SP是用于POS端查询会员时，返回相关的会员信息使用
--	DROP PROCEDURE IF EXISTS `SP_VIP_RetrieveNByMobileOrCardCode`;
--	CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_VIP_RetrieveNByMobileOrCardCode`(
--		OUT iErrorCode INT,
--		OUT sErrorMsg VARCHAR(64),
--		IN sPhone VARCHAR(11),
--		IN sCardCode VARCHAR(20)
--		)
--	BEGIN
--		
--		DECLARE iVipID INT;
--		DECLARE iWxVipID INT;
--		DECLARE iWxVipCardID INT;
--		DECLARE iWxVipCardDetailID INT;
--		DECLARE EXIT HANDLER FOR SQLEXCEPTION 
--		BEGIN
--			SET iErrorCode := 3;
--			SET sErrorMsg := '数据库错误';
--			ROLLBACK;
--		END;
--		
--		START TRANSACTION;
--			IF sPhone <> '' THEN
--				SELECT F_ID INTO iVipID FROM t_vip WHERE F_Mobile = sPhone;
--				SELECT F_ID INTO iWxVipID FROM t_wxvip WHERE F_VipID = iVipID;
--				SELECT F_ID INTO iWxVipCardID FROM t_wxvipcard WHERE F_WxVipID = iWxVipID;
--				SELECT F_ID INTO iWxVipCardDetailID FROM t_wxvipcarddetail WHERE F_WxVipCardID = iWxVipCardID;
--			ELSEIF sCardCode <> '' THEN
--		   		SELECT F_ID, F_WxVipCardID INTO iWxVipCardDetailID, iWxVipCardID FROM t_wxvipcarddetail WHERE F_Code = sCardCode;
--		   		SELECT F_WxVipID INTO iWxVipID FROM t_wxvipcard WHERE F_ID = iWxVipCardID;
--				SELECT F_VipID INTO iVipID FROM t_wxvip WHERE F_ID = iWxVipID;
--			END IF;
--			
--			IF iVipID IS NULL OR iWxVipID IS NULL OR iWxVipCardID IS NULL OR iWxVipCardDetailID IS NULL THEN
--				SET iErrorCode := 2;
--				SET sErrorMsg := '查询不到该会员的数据';
--			ELSE
--				SELECT 
--					F_ID, 
--					F_SN, 
--					F_CardID,
--					F_Status, 
--					F_Mobile, 
--					F_LocalPosSN, 
--					F_Sex, 
--					F_Logo, 
--					F_ICID, 
--					F_Name, 
--					F_Email, 
--					F_ConsumeTimes,
--					F_ConsumeAmount, 
--					F_District, 
--					F_Category, 
--					F_Birthday, 
--					F_Bonus, 
--					F_LastConsumeDatetime, 
--					F_Remark,
--					F_CreateDatetime, 
--					F_UpdateDatetime
--				FROM t_vip WHERE F_ID = iVipID;
--				
--				SELECT 
--					F_ID, 
--					F_VipID, 
--					F_PublicAccountOpenID, 
--					F_MiniProgramOpenID, 
--					F_UnionID, 
--					F_Nickname, 
--					F_Bonus, 
--					F_Balance, 
--					F_Sex, 
--					F_UserInfo, 
--					F_CustomFieldList, 
--					F_Name, 
--					F_Value, 
--					F_UserCardStatus, 
--					F_LastUsedDateTime
--				FROM nbr.t_wxvip WHERE F_ID = iWxVipID;
--				
--				SELECT 
--					F_ID, 
--					F_WxVipCardID, 
--					F_Code, 
--					F_CardID, 
--					F_BackgroundPicUrl, 
--					F_OldUserCardCode, 
--					F_IsGiveByFriend, 
--					F_FriendUserName, 
--					F_OuterStr, 
--					F_IsRestoreMemberCard, 
--					F_UnionId, 
--					F_MsgType, 
--					F_Event, 
--					F_ToUserName
--				FROM nbr.t_wxvipcarddetail WHERE F_ID = iWxVipCardDetailID;
--				
--				SET iErrorCode := 0;
--				SET sErrorMsg := '';
--			END IF;
--			
--		COMMIT;
--	END;